baseURL = 'https://romanthapa8848.github.io/'
languageCode = 'en-us'
title = 'Roman Thapa'
theme = 'roman'  # Add this line to specify the theme

[params]
# You can also customize some theme parameters here
description = "A sleek, minimalistic Hugo site using the Roman theme."
